export const ignores = [
  '**/.DS_Store',
  '**/node_modules/**/*',
  '**/.git/**/*',
  '**/.private/**/*',
  '**/.build/**/*',
  '**/.coverage/**/*',
  '**/.history/**/*',
  '**/.output/**/*',
  '**/.cache/**/*',
  '**/.temp/**/*',
  '**/.tmp/**/*',
  '**/.out/**/*',
  '**/.env*',
  '**/*-lock.*',
  '**/*.lock',
  '**/*.log*',
  '**/*.min.*',
  '**/*.d.ts',
  '**/LICENSE*',
  '**/package*',
  '**/dist/**/*',
  '**/build/**/*',
  '**/coverage/**/*',
  '**/public/**/*',
  '**/output/**/*',
  '**/cache/**/*',
  '**/temp/**/*',
  '**/tmp/**/*',
  '**/out/**/*',
  '**/LICENSE*',
]

export const ignoresConfig = {
  ignores,
}
